version: "3.5"
services:
  postgres-db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - default

networks:
  default:
    driver: "bridge"
